# Use root/example as user/password credentials
version: "3.1"

services:
  server-app:
    build: .
    environment:
      - CONNECTION_STRING=mongodb://root:example@mongo:27017/
    image: server-app
    depends_on:
      - mongo
    ports:
      - 8000:8000
    networks:
      - spm
    command: node dist/index.js

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - "mongodb_data:/data/db"
    networks:
      - spm
volumes:
  mongodb_data:

networks:
  spm:
